language: csharp
dist: trusty

addons:
  sonarcloud:
    organization: "unimibsoftengcourse1920"
    token:
      secure: "A0RYixq19sLUXRpG/DLOhQPCwXlpn+Mg1zWJxmtDEJm6FJ8my9KEskHQ6S3IJY+pK+1qkCVbzlSFmaDdpFTjRtnJWCgPU9MvG5BFZLMv+KTkDEYN86BOWJ/mwRY/I0ZaQnSmf3/roWPp11ej10e1dyPKkBJXWvr3kPPtrlIRiV61PobD/7NKJGanlbcu1n2jN8KJ8EmVzcjWz5Rc8UGk/up8ktd7pjGceCVHK6g5Nl/60C3tckHtACAHDV1AFrhtRwrhizptNJza/VDxv/QgCCWMNvxxKN6t/3SK014TJNXZveaWGF4MYMNJdXMWkKOlqXrb9htgQEOw1oP5N0RE7rZGu0nv8/GHDrDxFaBq9buUx1wQLp1Q3h9YI89ZzbcDe0kNY7FrxupY3NbXzGD9TvgBcQag7lirD/jzIi1Dh4Dt1AzltngJl4TgKUOZnZKbEgQl/5a3yUcVSqnBhgNvpzc9Ml6m73IpwPizKCvl5DSHU1TjkkTpv02mywd/35lJkCEi16VJCpToU3b8qDKZ2RpR/rNm5RfmmRjIjiirvQVEYnrR0Up64Tcm0je8ZM6kj7SxlagGUIy7Ca1BegOKv1euEeAKDbk7bH/bF0sptOgKaaLhzvDUI0Rt/Idsl2iDCSwj6rR44xz7BFrZD+s4iXfbA/8EwqtO9A3P7s0ldsI="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner
